-- # USED_GOODS_BOARD와 USED_GOODS_REPLY 테이블에서 
-- # 2022년 10월에 작성된 
-- # 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE 
FROM USED_GOODS_BOARD AS A, USED_GOODS_REPLY AS B 
WHERE A.BOARD_ID = B.BOARD_ID AND A.CREATED_DATE LIKE "2022-10%" 
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;

-- # Inner JOIN 사용