SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = "Python" OR SKILL_2 = "Python" OR SKILL_3 ="Python"
ORDER BY ID ASC;

--  WHERE 'Python' IN (SKILL_1, SKILL_2, SKILL_3) IN 연산자 쓰는 게 쿼리가 더 깔끔하네