SELECT B.ID, B.EMAIL, B.FIRST_NAME, B.LAST_NAME
FROM SKILLCODES A
JOIN DEVELOPERS B ON (A.CODE & B.SKILL_CODE) = A.CODE
WHERE A.CATEGORY = 'Front End'
GROUP BY B.ID, B.EMAIL, B.FIRST_NAME, B.LAST_NAME
ORDER BY B.ID ASC;