-- 코드를 입력하세요
# 기본 키 FLAVOR, 외래 키는 FIRST_HALF 테이블의 SHIPMENT_ID는 JULY 테이블의 SHIPMENT_ID
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN JULY B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY (A.TOTAL_ORDER + SUM(B.TOTAL_ORDER)) DESC
LIMIT 3;