/* 최종 테이블의 컬럼 선택 (CAR_ID, CAR_TYPE, FEE) */
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE*30*((100-DISCOUNT_RATE)/100),0) AS FEE

/* 메인 테이블(CAR_RENTAL_COMPANY_CAR) 에서 CAR_TYPE이 '세단', 'SUV'인 것만 추출 */
FROM 
(SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE IN ('세단', 'SUV')) AS A

/* 조인 테이블(CAR_RENTAL_COMPANY_DISCOUNT_PLAN) 에서 DURATION_TYPE이 '30일 이상' 인 것만 추출 */
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B 
        ON A.CAR_TYPE = B.CAR_TYPE AND DURATION_TYPE = '30일 이상'

/* 최종 테이블에서 START_DATE와 END_DATE 사이에 "2022-11-01" 또는 "2022-11-31"가 포함되지 않는 CAR_ID 행을 선택 */
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE ("2022-11-01" BETWEEN START_DATE AND END_DATE)
        OR ("2022-11-31" BETWEEN START_DATE AND END_DATE)) 

/* CAR_ID 그룹화 (혹은 GROUP BY 대신 최종 테이블의 컬럼 선택 시 distINct로 대체 가능) */
GROUP BY CAR_ID

/* CAR_ID 그룹 중 FEE 가 500,000원 이상 2,000,000원 이하인 그룹 선택 */
HAVING FEE >= 500000 AND FEE < 2000000

/* FEE 기준 내림차순 -> CAR_TYPE 기준 오름차순 -> A.CAR_ID 기준 내림차순 */
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC